version: "3.8"
services:
  redis:
    image: redis:7
    container_name: redis_app

  celery:
    container_name: celery_app
    build: .
    command: celery -A celery_app worker -l debug
    volumes:
      - .:/app/celery
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    container_name: celery_beat_app
    build: .
    command: celery -A celery_app beat -l info
    volumes:
      - .:/app/celery
    env_file:
      - .env
    depends_on:
      - redis

  app:
    build:
      context: .
    container_name: tenderplan_app
    env_file:
      - .env
    ports:
      - 1528:8000
    depends_on:
      - redis
      - celery
      - celery-beat